# Generated by Django 3.2.5 on 2021-09-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_midifile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MidiFile',
        ),
        migrations.AlterModelTable(
            name='recordfile',
            table='ReocrdFileList',
        ),
    ]
