# Generated by Django 3.2.7 on 2021-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20210924_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordFileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ReocrdFileList',
            },
        ),
        migrations.DeleteModel(
            name='RecordFile',
        ),
    ]
