# Generated by Django 3.2.7 on 2021-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_auto_20210924_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfilelist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
