# Generated by Django 3.2.7 on 2021-11-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wav2midi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MidiFile',
        ),
    ]
